# Generated by Django 5.0.6 on 2024-07-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_first_name', models.CharField(max_length=100)),
                ('Patient_last_name', models.CharField(max_length=100)),
                ('Patient_profile_picture', models.ImageField(upload_to='Patient/')),
                ('Patient_username', models.CharField(max_length=100)),
                ('Patient_email', models.EmailField(max_length=254)),
                ('Patient_password', models.CharField(max_length=100)),
                ('Patient_confirm_password', models.CharField(max_length=100)),
                ('Patient_city', models.CharField(max_length=100)),
                ('Patient_state', models.CharField(max_length=100)),
                ('Patient_pincode', models.IntegerField()),
            ],
        ),
    ]
