# Generated by Django 5.0.6 on 2024-08-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_book_book_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_appointment',
            old_name='doctor',
            new_name='d',
        ),
    ]
